export const TODO_CREATE = 'todocreate'
export const TODO_UPDATE = 'todosupdate'
export const TODO_DELETE = 'todosdelete'
export const TODO_FETCH_LIST = 'todofetchlist'
export const TODO_CLEAR_LIST = 'todoclearlist'
